### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [stavxyz/tox-pyenv#20]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by gaborbernat** [comment]
From the lack of response here I assume we'll need to fork the project under a new name then :+1:

**Comment by stavxyz** [comment]
@gaborbernat sorry for the delay. I am happy to move the project

**Comment by gaborbernat** [comment]
Please transfer it to me then and I'll move it under tox-dev :blush:
